name: sleep_guard
description: Sleep guard app
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  screen_brightness: ^2.0.0
  android_intent_plus: ^6.0.0
  workmanager: ^0.5.2

flutter:
  uses-material-design: true